---
deployment:
  tasks:
    - export DEPLOYPATH=/home/altayapp/public_html
    - export REPOPATH=/home/altayapp/repositories/altakassus-web
    - /bin/cp -R $REPOPATH/public/* $DEPLOYPATH/
    - /bin/sed -i "s|__DIR__\\.'/../laravel/storage/framework/maintenance.php'|'$REPOPATH/storage/framework/maintenance.php'|g" $DEPLOYPATH/index.php
    - /bin/sed -i "s|__DIR__\\.'/../laravel/vendor/autoload.php'|'$REPOPATH/vendor/autoload.php'|g" $DEPLOYPATH/index.php
    - /bin/sed -i "s|__DIR__\\.'/../laravel/bootstrap/app.php'|'$REPOPATH/bootstrap/app.php'|g" $DEPLOYPATH/index.php