---
deployment:
  tasks:
    - export DEPLOYPATH=/home/altayapp/public_html/
    - /bin/cp -R public_html/public/* $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/.git
    - /bin/rm -f $DEPLOYPATH/.cpanel.yml